### ISSUE TITLE
It is impossible to create ZeroPrice Tier in PriceResource.

### ISSUE THREAD

**Issue by umisora** [lukasaron/terraform-provider-stripe#1]
I chose this repository out of several StripeProvider repositories because it is the most recently maintained and well documented. Thank you for the development!! 

By the way, I noticed that I can't set ZeroPrice in the PriceObject tier settings.

For example, in someone else's Provider, the [! = nil condition](https://github.com/franckverrot/terraform-provider-stripe/blob/main/stripe/resource_stripe_price.go#L289), but

This product is [! = 0 condition](https://github.com/lukasaron/terraform-provider-stripe/blob/main/stripe/resource_stripe_price.go#L351) for this product.

I noticed this when I tried to create a TierPrice where less than 100 users are free and 101 users are paid, but I couldn't create it with Terraform.

Proposal.
Would you like to modify it to accept zero-price?

**Comment by lukasaron** [comment]
Indeed, let me investigate and update this Price resource during a weekend.

**Comment by lukasaron** [comment]
Conditions removed and the release should be in a few minutes. Thanks for reporting this and I hope you will also enjoy this provider. When you have something in the future you can also perform the pull request and become a contributing member of this provider.

**Comment by umisora** [comment]
Thank you for fix this issue!
