### ISSUE TITLE
Metadata entries not removed

### ISSUE THREAD

**Issue by internethostage** [lukasaron/terraform-provider-stripe#15]
I noticed that metadata entries are only added or the value updated, but not removed or key updated.

For example if I add a metadata field to a resource (I tested this on price)

```
  metadata = {
    foo = "bar"
  }
```

Then I change it to
```
  metadata = {
    bar = "foo"
  }
```

I end up with `foo` and `bar` as metadata keys with their respective values.
My expectation is that the `foo` key should have been removed.

<img width="310" alt="Screen Shot 2022-06-15 at 4 34 03 PM" src="https://user-images.githubusercontent.com/17835977/173921994-2e26575f-48e7-40b3-95ea-298b64ec9ba8.png">

I have resolved this by setting `foo = ""` and running an apply, then removing from the terraform resource declaration, but I think we could resolve this better on the provider. This is necessary otherwise the terraform plan always picks this up as a pending change when comparing to source.

I believe that the fix is to send to stripe the value of the keys to be removed as an empty string.

**Comment by internethostage** [comment]
nvm, my bad

**Comment by lukasaron** [comment]
I think it's a good idea to revisit the current solution. Thanks for bringing this up to the light!

**Comment by lukasaron** [comment]
Metadata should reflect the removal in version v1.6.3
