### ISSUE TITLE
Create webhook with "connect" endpoint type

### ISSUE THREAD

**Issue by kenske** [lukasaron/terraform-provider-stripe#16]
When you create a webhook on Stripe's website,  you are given an option that says "Listen to events on connected accounts". Checking this option will change the endpoint type. Does the `stripe_webhook_endpoint` resource support this option? I couldn't see an argument in the docs that looked like it would fit.

**Comment by lukasaron** [comment]
I am gonna add this flag in a few minutes

**Comment by kenske** [comment]
Thank you!
