### ISSUE TITLE
Make a new release please!

### ISSUE THREAD

**Issue by internethostage** [lukasaron/terraform-provider-stripe#23]
Hello @lukasaron , just noticed there was an error with the `goreleaser` github action. https://github.com/lukasaron/terraform-provider-stripe/actions/runs/3202577144/jobs/5231736372

Any chance you can have a look so we can get a new release?
Thank you for your quick response :)

**Comment by lukas-aron-archa** [comment]
I will release it soon. I just don't wanna spend night on debugging release process.

**Comment by lukasaron** [comment]
Released successfully finished
