### ISSUE TITLE
How to specify Product ID?

### ISSUE THREAD

**Issue by arai-ta** [lukasaron/terraform-provider-stripe#31]
Hi,

I want to create a Product by specifying an ID, but it doesn't work.
Does this provider supports specifying product IDs?

My .tf is following;

```main.tf
terraform {
  required_providers {
    stripe = {
      source  = "lukasaron/stripe"
      version = "= 1.6.3"
    }
  }
}

provider "stripe" {}

resource "stripe_product" "myplan" {
  id   = "prod_myplan"
  name = "My Plan"
}
```

apply results;

```console
Terraform used the selected providers to generate the following execution plan.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # stripe_product.myplan will be created
  + resource "stripe_product" "myplan" {
      + active = true
      + id     = (known after apply)
      + name   = "My Plan"
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

stripe_product.myplan: Creating...
stripe_product.myplan: Creation complete after 0s [id=prod_NSKLZrMRKodugv]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```

I expected the ID to be `prod_myplan`, but it is actually `prod_NSKLZrMRKodugv`.

I reffered:

- https://stripe.com/docs/api/products/create#create_product-id
- https://registry.terraform.io/providers/lukasaron/stripe/latest/docs/resources/stripe_product#id

Versions:

```
Terraform v1.3.9
on darwin_arm64
+ provider registry.terraform.io/lukasaron/stripe v1.6.3
```

**Comment by lukasaron** [comment]
Hello,
According to the Stripe API documentation:

"An identifier will be randomly generated by Stripe. You can optionally override this ID, but the ID must be unique across all products in your Stripe account." 

Therefore I let Stripe generate the ID. However, when there is a desire to have individual ID I can update the logic. 

You don't usually need the ID of the product. 

May I ask what is the reason or use case?

**Comment by arai-ta** [comment]
Of course. Thanks for the reply.

I am trying to replace the subscription function of an existing web application with Stripe.
There are multiple ways to map Products in the application to Products in Stripe.

For example;

* Embed the generated Stripe Product ID in the application code
* Set the application identifier in the Product metadata
* Set the Product ID as the application identifier

I think the last case is one of the simpler solutions.

To use this method, it is necessary to set the specified product ID in multiple environments, including Live and Test mode.
I wanted to use Terraform and this Stripe Provider for this purpose.

Also, the document following suggested using the same ID in Live and Test mode.

https://stripe.com/docs/development/checklist#:~:text=use%20the%20same%20ID%20values

> When recreating necessary objects in live mode, be certain to use the same ID values (for example, the same plan ID, not the same name) to guarantee your code will continue to work without issue.

So, I think if Terraform can create a Product resource by specifying the ID, it would be useful. :)

Hope this helps your understanding.

**Comment by arai-ta** [comment]
I've tried version 1.6.6 and confirmed that the `product_id` field works.
Thank you!

**Comment by arai-ta** [comment]
Hello @lukasaron,
I wrote a blog about how this Stripe Provider has helped me in my work.
It is written in Japanese, but if you would like to read it. Thank you!!
https://creators-note.chatwork.com/entry/terraform-meets-stripe

**Comment by lukasaron** [comment]
Thanks a lot @arai-ta I am glad the Stripe provider helped you achieve your goals!
Unfortunately, my Japanese is very bad and I believe you wrote something nice there.
