### ISSUE TITLE
Price - missing attribute currency_options

### ISSUE THREAD

**Issue by qck4fun** [lukasaron/terraform-provider-stripe#33]
Hey, I've been trying to use your provider to create some price objects in Stripe, but have found that you currently do not support `currency_options` attribute (https://stripe.com/docs/api/prices/create#create_price-currency_options).

Would you be willing to add it?

**Comment by lukasaron** [comment]
Hello @qck4fun ,

Indeed, I can add the `currency_option` into the price object.

**Comment by landsman** [comment]
That would be wonderful!

**Comment by lukasaron** [comment]
Please try the provider version v1.7.0.
