### ISSUE TITLE
Possible to create a Plan with multiple currencies?

### ISSUE THREAD

**Issue by danryu** [lukasaron/terraform-provider-stripe#36]
From the Stripe API docs it doesn't seem to be possible to create a Plan with multiple currencies, so I'm guessing it's not possible with this provider too ...
https://stripe.com/docs/api/plans/create

As it's not possible to update a Plan with additional currencies also, I am wondering how Stripe expect businesses to present more than one currency when using the API.

Any input appreciated.

**Comment by lukasaron** [comment]
Hello @danryu ,
Stripe encourages the use of Price as opposed to Plan thus the support will be more in the Price API. 
In the Price API, there is a way how to add multiple currencies. I would need to implement this feature.

**Comment by lukasaron** [comment]
Please try the provider version v1.7.0.
