### ISSUE TITLE
API_KEY is not read when the provider has an alias

### ISSUE THREAD

**Issue by DennisVonDerBey** [lukasaron/terraform-provider-stripe#38]
Hi, we noticed a bug in our repository that if you alias your stripe provider like this:

```
provider "stripe" {
  alias   = "stripe_account_1"
  api_key = var.stripe_account_1_api_key
}
```

it will not read out the `api_key` property correctly. It will therefore ask you for it in the manual prompt and fail in CI/CD. With the env var `STRIPE_API_KEY` it works.

**Comment by lukasaron** [comment]
I think the issue is in the Terraform state. Looks like you created resources with the provider without the alias. Could you please try to keep the stripe provider without the alias as it is and create a new one with the new alias and update resources to use that alias provider?

**Comment by DennisVonDerBey** [comment]
Ahh that makes total sense. Looking at our git it is really what happened. Thing is we didn't really need the alias in the first place, but that sounds like a logical thing. Thank you for the help :)
