### ISSUE TITLE
Associate a default Price for a Product

### ISSUE THREAD

**Issue by jabinb** [lukasaron/terraform-provider-stripe#39]
There doesn't seem to be a way to [associate a `default_price` to a Product](https://stripe.com/docs/api/products/update#update_product-default_price).

I assume this is because it's not possible to do it at creation of the Product (Price depends on the creation of the Product). One idea would be to model it like an "attachment", akin to [aws_iam_user_policy_attachment](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_user_policy_attachment) which can happen after both the Product and Price exist.

As a workaround I'm using `hashicorp/http` to send the Product update request manually.

```tf
data "http" "stripe_api_set_default_price" {
  url = "https://api.stripe.com/v1/products/${stripe_product.my_product.id}"
  method = "POST"
  request_headers = {
    Accept = "application/json"
    "Content-Type" = "application/x-www-form-urlencoded"
    Authorization = sensitive("Bearer ${var.api_key}")
  }

  request_body = "default_price=${stripe_price.my_price.id}"

  lifecycle {
    postcondition {
      condition     = contains([200, 201, 204], self.status_code)
      error_message = "Stripe default price POST request returned invalid status code"
    }
  }

  depends_on = [stripe_price.my_price]
}

```

**Comment by lukasaron** [comment]
I've decided to separate the product resource and the price resource. Therefore you have more control over the change of the price. In order to solve your issue I would recommend creating a product and using the product ID in the price resource.
