### ISSUE TITLE
429 Rate Limits

### ISSUE THREAD

**Issue by wscourge** [lukasaron/terraform-provider-stripe#40]
Context: I create 63 subscription products with 2 prices each, and hit the HTTP 429 wall.

> Error: {"code":"rate_limit","doc_url":"https://stripe.com/docs/error-codes/rate-limit","status":429,"message":"Testmode request rate limit exceeded, the rate limits in testmode are lower than livemode. You can learn more about rate limits here https://stripe.com/docs/rate-limits.","type":"invalid_request_error"}
│
│   with stripe_product.local_template["abp"],
│   on stripe.tf line 91, in resource "stripe_product" "local_template":
│   91: resource "stripe_product" "local_template" {

More context here: https://stripe.com/docs/error-codes/rate-limit

> Running a large volume of closely-spaced requests can lead to rate limiting. Often this is part of an analytical or migration operation. When engaging in these activities, you should try to control the request rate on the client side (see [Handling limiting gracefully](https://stripe.com/docs/rate-limits#handling-limiting-gracefully)).

Cheers, and keep up the good work.

**Comment by lukasaron** [comment]
Hello @wscourge ,

Thanks for reporting this!

I read the documentation you mentioned and fortunately the `live` version has higher throughput. I am pretty sure that handling the rate limit can be involved in this provider. Let me mark this one as an enhancement.

**Comment by wscourge** [comment]
Wow, such a fast response, nice!

It is true the `live` version has a _higher_ throughput, but it is still _not unlimited_, and it'd be good to handle this at the provider level - thank you!

**Comment by lukasaron** [comment]
Please see the latest version v1.7.4 which includes the rate-limiting handler.
