### ISSUE TITLE
"An entry in the tiers array is missing an amount."

### ISSUE THREAD

**Issue by juliandm** [lukasaron/terraform-provider-stripe#45]
The error in the title appears when following the example of tiers in the terraform provider documentation of the resource stripe_price

Workaround is using `flat_amount_decimal` attribute and removing a for free tier

**Comment by lukasaron** [comment]
Could you please share the HCL resources so I can replicate your issue?

**Comment by juliandm** [comment]
It happened while taking the example code from the provider, so this is directly copy&pasted from the documentation. unit_amount 0 makes problems

```hcl
// tiered price for the product
resource "stripe_price" "price" {
  // product needs to be defined
  product        = stripe_product.product.id
  currency       = "aud"
  billing_scheme = "tiered"
  tiers_mode     = "graduated"

  # free up to ten
  tiers {
    up_to       = 10
    unit_amount = 0
  }

  tiers {
    up_to       = 100
    unit_amount = 300
  }

  tiers {
    up_to       = -1
    unit_amount = 100.5
  }

  recurring {
    interval        = "week"
    aggregate_usage = "sum"
    interval_count  = 2
    usage_type      = "metered"
  }
}
```

**Comment by markmssd** [comment]
I'm having the same issue. First the 3rd tier needs to be changed to `unit_amount_decimal = 100.5`. Then, when it fails and looking at the stripe logs, this is what it receives:
```
"tiers": {
    "0": {
      "up_to": "10"
    },
    "1": {
      "unit_amount": "300",
      "up_to": "100"
    },
    "2": {
      "up_to": "inf",
      "unit_amount_decimal": "100.5"
    }
  }
```

Notice that the first tier is missing an amount. @juliandm did you find a resolution?

**Comment by prithage** [comment]
Any update on this @lukasaron ?

**Comment by lukasaron** [comment]
@juliandm  @markmssd @prithage Please see the latest version 1.8.0.

**Comment by markmssd** [comment]
It worked great, thank you @lukasaron !
