### ISSUE TITLE
using "unit_amount_decimal" leads to a change in "unit_amount" on every apply

### ISSUE THREAD

**Issue by juliandm** [lukasaron/terraform-provider-stripe#48]
![image](https://github.com/lukasaron/terraform-provider-stripe/assets/22846154/f9325e48-9b48-4d3b-b883-e72a4d1aec03)

Reproduce:
- create a stripe price https://registry.terraform.io/providers/lukasaron/stripe/latest/docs/resources/stripe_price with the attribute "unit_amount_decimal" set
- create another dummy resource
- make changes to the dummy resource

You will see that the price resource is destroyed and recreated every time although nothing was changed in it

**Comment by lukasaron** [comment]
I was able to replicate the issue only when I put unit_amount_decimal as INTEGER value as opposed to FLOAT. Unfortunately, when unit_amount_decimal is set to INT (for example 1299) the Stripe SDK populates both values (unit_amount and unit_amount_decimal). Consequently, the Terraform state is confused.
