### ISSUE TITLE
[Customer Portal] subscription_update.products always appear as changed 

### ISSUE THREAD

**Issue by aliabbasrizvi** [lukasaron/terraform-provider-stripe#49]
May be a known issue, but I noticed that any time I do a `terraform apply`, customer portal always suggests `products` under `subscription_product` have changed. Wanted to check if there is a workaround or if I am doing something incorrectly.

Thank you

**Comment by lukasaron** [comment]
I have a feeling it's been fixed by: https://github.com/lukasaron/terraform-provider-stripe/pull/51

**Comment by aliabbasrizvi** [comment]
Just tried this and it is working well. Thank you @lukasaron and @internethostage .
