### ISSUE TITLE
Feature list for product

### ISSUE THREAD

**Issue by aliabbasrizvi** [lukasaron/terraform-provider-stripe#50]
Hi

Is it possible to do feature list for product? I couldn't find anything for it.

**Comment by lukasaron** [comment]
Hello @aliabbasrizvi ,

I think the feature list is a good ideat! Let me add this to the enhancement list.

**Comment by marcinkaluza** [comment]
Having a features on products would be really great for anyone bulding a Saas business.

**Comment by lukasaron** [comment]
@aliabbasrizvi @marcinkaluza Please see the latest version [1.8.2].

**Comment by marcinkaluza** [comment]
Thx a lot @lukasaron, I was about to implement it myself but looking at the source code I noticed it's already there!
