### ISSUE TITLE
Portal is_default flag

### ISSUE THREAD

**Issue by marcinkaluza** [lukasaron/terraform-provider-stripe#57]
Stripe API supports "is_default" attribute on the portal configuration object (https://stripe.com/docs/api/customer_portal/configuration) which indicates that the configuration can be seen and edited in the stripe dashboard/portal. It would be great to be able to have this attribute in the stripe_portal_configuration resource..

**Comment by lukasaron** [comment]
Hi @marcinkaluza,
Thanks for the proposal of this attribute. I am trying to find a way to set this flag in this section of the API Doc: https://stripe.com/docs/api/customer_portal/configurations/create and I am not successful in determining it.

**Comment by lukasaron** [comment]
is_default value is going to be exported in the Customer Portal Configuration. Please see the documentation of the newest version 1.9.2.
