### ISSUE TITLE
Unable to remove a product when it has prices

### ISSUE THREAD

**Issue by jon-armen** [lukasaron/terraform-provider-stripe#60]
Error: {"status":400,"message":"This product cannot be deleted because it has one or more user-created prices.","request_id":"req_...","request_log_url":"[https://dashboard.stripe.com/test/logs/req_...?t=1705116524","type":"invalid_request_error"}](https://dashboard.stripe.com/test/logs/req_...?t=1705116524%22,%22type%22:%22invalid_request_error%22})
│

This provider already archives prices when deleted from state.  Is it possible to modify the provider so that when a product is deleted, if it has prices, the product will be archived instead of deleted?

**Comment by lukasaron** [comment]
Hi @jon-armen ,
I like the proposal and I think I can implement this. 
Thank You for this!

**Comment by lukasaron** [comment]
The proposal from @jon-armen was accepted and implemented and it is part of version 1.9.3.
