### ISSUE TITLE
Recurring price without interval_count will always show change

### ISSUE THREAD

**Issue by gtownend** [lukasaron/terraform-provider-stripe#63]
If you have a price with a recurring block but do not set the `interval_count` it will always show in a plan as being changed to null.

This is because when it is set there is no default value but when it is read from the stripe API there always is a value, which then gets written into the state.

**Comment by lukasaron** [comment]
Hi @gtownend,
Thanks for reporting this and I can confirm I was able to replicate the issue.

When the field `interval_count` is omitted the value that comes from the Stripe is set to `1` as default. Let me perform a fix.

**Comment by lukasaron** [comment]
I've let the empty (0) value propagate into the Stripe API which consequently fails as this value is required to be at least 1.

Thanks for opening this ticket @gtownend and you should be able to see the fix in version 1.9.5.
