### ISSUE TITLE
tax_behavior on price resource might be misspelled

### ISSUE THREAD

**Issue by berenteb** [lukasaron/terraform-provider-stripe#66]
We changed the tax behavior on the Stripe admin panel, which "cannot be updated later on". To match the settings in our terraform code, I changed `tax_behaviour` property to match the setting on the site. This property is accepted in this form, including the letter U. However the Stripe API does not recognize this, since it specifies `tax_behavior` (without the U). I noticed that the `currency_options` object also specifies `tax_behavior` (without the U).

Currently I am bumping into this error message with the U: You cannot update `tax_behavior` field once it has been specified.

Without the U, I get the following: An argument named "tax_behavior" is not expected here. Did you mean "tax_behaviour"?

**Comment by lukasaron** [comment]
This is a good catch! I can see the appearance of both `behavior` and `behaviour` in the code. 

1. The code will change according to the Stripe API doc in this manner.
2. As this is a breaking the compatibility a major version upgrade would be necessary.

**Comment by lukasaron** [comment]
This has been fixed and released under version 2.0.0.

**Comment by berenteb** [comment]
Thanks a lot, we appreciate it!
