### ISSUE TITLE
connect argument is not picked up

### ISSUE THREAD

**Issue by Makzemann** [lukasaron/terraform-provider-stripe#67]
Expected behaviour: set hosted endpoint type to 'Connect' with use of optional boolean 'connect' set to true, actual behaviour is endpoints set to default 'Account'

![image](https://github.com/lukasaron/terraform-provider-stripe/assets/76131710/9752e2c6-af34-4373-b9ad-a59341857713)
![image](https://github.com/lukasaron/terraform-provider-stripe/assets/76131710/71f65eeb-cb46-48e0-9af9-23682b8bc5b3)

**Comment by lukasaron** [comment]
Hello @Makzemann ,

Firstly, Thanks for using my Stripe Provider!

Secondly, I was trying to replicate your issue and I was not successful. 

```hcl
resource "stripe_webhook_endpoint" endpoint {
    url = "http://loc.com.au/webhook"
    connect = true
    enabled_events = [
        "account.updated"
    ]
}
```

![Screenshot 2024-06-06 at 10 34 48 AM](https://github.com/lukasaron/terraform-provider-stripe/assets/2580893/e1fc69a1-34ba-4904-a13c-5f6fdb069240)

**Comment by Makzemann** [comment]
Hi @lukasaron then it must be something missing on my side, thanks for checking!
