### ISSUE TITLE
Update to sdk 78.10

### ISSUE THREAD

**Issue by Chikouni** [lukasaron/terraform-provider-stripe#68]
Hello, 

It's possible to update the stripe sdk to have the new stripe API VERSION with "2024-04-10", instead of actually : 
2023-10-16 ?

best regards,

**Comment by lukasaron** [comment]
Hello @Chikouni,

Thanks for raising this question! 

Indeed, the upgrade is on the roadmap.

**Comment by Chikouni** [comment]
@lukasaron Wonderful !! <3 

If you want help for the PR, i'm available ;)

See u

**Comment by lukasaron** [comment]
@Chikouni Closing this issue as the upgrade of the Stripe SDK (v78) is gonna be used since Stripe Terraform version 3.0.0.
