### ISSUE TITLE
Question with Custom Unit Amount in Stripe Price Resource

### ISSUE THREAD

**Issue by fabius11** [lukasaron/terraform-provider-stripe#75]
First of all, thank you for creating this excellent Stripe provider for Terraform.
It has been incredibly helpful in managing our Stripe resources.
We appreciate your hard work and dedication to the project.

## Description

I'm trying to create a Stripe Price resource with a custom unit amount using your provider. However, I'm encountering issues with the syntax and configuration. Using `v3.0.2`.

## Current Code and Errors

Initially, I tried to add the `custom_unit_amount` block at the top level:

```hcl
resource "stripe_price" "prepaid_credits_price" {
  currency = "usd"
  product  = stripe_product.<SOME_OTHER_PRODUCT>.id
  nickname = "prepaid-user-can-enter-between-5-and-500"

  custom_unit_amount {
    enabled = true
    minimum = 500
    maximum = 50000
    preset  = 1000
  }
}
```

this resulted in the error: `Blocks of type "custom_unit_amount" are not expected here.`

Since the custom_unit_amount block wasn't accepted at the top level, I tried to include it within the `currency_options` block. Initially, I attempted to use "usd" as the currency, but received an error stating that the currency option matches the top-level currency. So, I switched to using "jpy" as an example:

```hcl
resource "stripe_price" "prepaid_credits_price" {
  currency = "usd"
  product  = stripe_product.<SOME_OTHER_PRODUCT>.id
  nickname = "prepaid-user-can-enter-between-5-and-500"

  currency_options {
    #currency = "usd"  # error: "You are specifying a currency option that matches the top-level currency for this price. Please remove this currency option and it will be added automatically on creation."
    currency = "jpy"
    custom_unit_amount {
      enabled = true
      minimum = 500
      maximum = 50000
      preset  = 1000
    }
  }
}
```
However, this also resulted in an error:
`Cannot specify custom_unit_amount on a currency_option without also specifying custom_unit_amount on the top level price, or vice versa.`

Could you help on this? Aplogies if my explanation and details are not clear.

I understand the whole process is different but the following Python code worked when I tested previously and trying to create it from terraform.

```python
stripe.Price.create(
    currency="usd",
    product=<SOME_OTHER_ID_PRODUCT_ID>,
    nickname="prepaid-user-can-enter-between-5-and-500",
    custom_unit_amount= {
        "enabled": True,
        "minimum": 5 00,
        "maximum": 50000,
        "preset": 1000,
    }
)
```

Thanks.

**Comment by lukasaron** [comment]
Hello @fabius11 ,

Thank You for your question and I would say your explanation is pretty decent.

I did a quick test and seems there is a bug in the provider which needs to be fixed. I'm going to change this issue from question to bug and I hope I'll be able to unblock you soon.

**Comment by lukasaron** [comment]
@fabius11 I have identified the whole `custom_unit_amount` block was missing in the code. Please refer to the update documentation of the `price` resource (which is your first code attempt from this issue) and try it in the latest version 3.1.0.

Thanks a lot again for reporting this. I believe we made it one step further to a better Terraform Stripe Provider.

Cheers,
Lukas

**Comment by fabius11** [comment]
@lukasaron Thank you for the quick fix and update. I will try the latest version 3.1.0 this week and will contact you if I encounter any issues. Once again, I truly appreciate it!
