### ISSUE TITLE
[feature request] Support Product Features (Entitlements)

### ISSUE THREAD

**Issue by cthiebault** [lukasaron/terraform-provider-stripe#77]
Thanks for your great work here :-)

It would be nice if this provider support the new Stripe [Entitlements](https://docs.stripe.com/billing/entitlements) feature.
We would need to be able to define the features and attache them to products.

**Comment by lukasaron** [comment]
Thank You @cthiebault I am going to explore options here.

**Comment by lukasaron** [comment]
Hi @cthiebault ,

Entitlements Feature and Product Feature resources have been implemented. Please try them in the new version 3.2.0.

**Comment by cthiebault** [comment]
Awesome!!
It works perfectly!

Thanks for your reactivity :-)
