### ISSUE TITLE
importing price with tiered/graduated price

### ISSUE THREAD

**Issue by dbarrosop** [lukasaron/terraform-provider-stripe#80]
Hello,
thanks for this awesome terraform provider. I am trying to import a price with a tiered/graduate scheme and looks like the tiers aren't correctly imported:

```
$ terraform state show stripe_price.xxx
# stripe_price.xxx:
resource "stripe_price" "xxx" {
    active         = true
    billing_scheme = "tiered"
    currency       = "usd"
    id             = "price_xxxx"
    lookup_key     = null
    metadata       = {}
    nickname       = null
    product        = "prod_xxx"
    tax_behavior   = "inclusive"
    tiers_mode     = "graduated"
    type           = "recurring"

    recurring {
        aggregate_usage = "max"
        interval        = "month"
        interval_count  = 1
        usage_type      = "metered"
    }
}
```

This is a problem because if I try to apply afterwards it wants to add all the tiers causing the price to be destroyed and recreated.

Regards

**Comment by lukasaron** [comment]
Hi @dbarrosop,

Thank You for using the Terraform Stripe Provider and also reporting issues!

I've found the bug and please try the next version 3.2.1 which should give you tier levels for price resource during import.

**Comment by lukasaron** [comment]
@dbarrosop,

Thanks for these points! It helps me understand your use case and also improve this provider.

Let me investigate on my side.

**Comment by lukasaron** [comment]
Please have a look at the latest release.
