### ISSUE TITLE
connect argument is not picked up

### ISSUE THREAD

**Issue by ralbertazzi** [lukasaron/terraform-provider-stripe#81]
Same as #67 .

I'm trying to import an existing Connect webhook. I can list it through `https://api.stripe.com/v1/webhook_endpoints` and find:
```json
{
      "id": "we_...",
      "object": "webhook_endpoint",
      "api_version": null,
      "application": "ca_...",
      ...
      "livemode": true,
      "status": "enabled",
      "url": "..."
    }
```

note how `application` is set, differently from other non-Connect webhooks where `application: null`.

If I try to import the webhook on Terraform and run `terraform apply` I get
```
-/+ resource "stripe_webhook_endpoint" "connect_old" {
      ~ connect        = false -> true # forces replacement
      ~ id             = "we_..." -> (known after apply)
      - metadata       = {} -> null
      + secret         = (sensitive value)
        # (4 unchanged attributes hidden)
    }
```

Right now I managed to import it while keeping `connect = false`, although it's an incorrect representation of my Stripe webhook.

**Comment by ralbertazzi** [comment]
I forgot to mention that the API version of my webhook is `2019-05-16`, I don't know if it makes any difference. However I tried creating a new Connect webhook by hand using `2024-06-20` as API version and it gets the same JSON representation. Not how `2019-05-16` is my default account version.

By checking the codebase it looks like we could solve it by checking if the `account` field is not null in [here](https://github.com/lukasaron/terraform-provider-stripe/blob/main/stripe/resource_stripe_webhook_endpoint.go#L100)

**Comment by lukasaron** [comment]
Hello @ralbertazzi,

Thanks for using the Stripe Provider!

Under the hood, I am using the official Stripe Go SDK implementation which is based on the official API: https://docs.stripe.com.

When you are importing the existing Webhook the "Retrieve a webhook endpoint" is executed: `https://docs.stripe.com/api/webhook_endpoints/retrieve`. Unfortunately, there isn't a `connect` field in the response. On top of that, there isn't any way you can update this field therefore the full removal & creation of new resources is required. You can see, what fields are modifiable based on this: `https://docs.stripe.com/api/webhook_endpoints/update`.


When you import an existing Stripe Webhook into the Terraform -> You need to manually update the `stripe_webhook_endpoint` from the terraform state: `terraform.tfstate` and from the Stripe when some values are missing.

Please let me know when there are any other questions.

**Comment by ralbertazzi** [comment]
@lukasaron I called the retrieve endpoint with my Stripe Connect webhook and I still get the `application` field. Note how I'm not suggesting to look for a `connect` field in my previous message, but an `application` field:
```json
{
  "id": "we_...",
  "object": "webhook_endpoint",
  "api_version": null,
  "application": "ca_...",
  "created": 1606897502,
  "description": "...",
  "enabled_events": [
   ...
  ],
  "livemode": true,
  "metadata": {},
  "status": "enabled",
  "url": "..."
}
```

Also, apologies if I gave the impression that I want to _update_ my webhook. I do not. I want to import an existing Connect webhook endpoint. What I'm saying is that when importing it I need to set the terraform field `connect = false` in order to let Terraform not detect a diff, even though it doesn't reflect reality.

To me it sounds like my suggestion to read the `application` JSON field in [here](https://github.com/lukasaron/terraform-provider-stripe/blob/main/stripe/resource_stripe_webhook_endpoint.go#L100) is still valid. Could you please keep the issue open? 🙏

**Comment by lukasaron** [comment]
Hi @ralbertazzi,

I had an impression we were talking about the `connect` field based on the `connect argument is not picked up` title. My bad, sorry about that.

I have a feeling I understand what you are referring to. Just to be sure let me summarize what you would like to have:
* The `application` field is neither possible to set or update (this field is read-only).
* The `application` field should be populated and stored in the state. 
* This `application field should be accessible from the attribute reference.

Please let me know whether this reflects the issue.

Cheers,
Lukas

**Comment by ralbertazzi** [comment]
Hi Lukas, I believe that's it! From a user standpoint this is what I expect. Probably some of this is already implemented:
- Creating a webhook with the Terraform parameter `connect = true` should result in setting the [connect](https://docs.stripe.com/api/webhook_endpoints/create#create_webhook_endpoint-connect) API parameter of the Stripe create webhook endpoint
- The state should store the `account` API parameter that is returned in both the LIST and GET webhook APIs and should be used to understand whether the webhook is a Connect webhook or a normal webhook.

Probably some confusion comes from the fact that Stripe allows a `connect` API parameter when creating the webhook but then returns the same information through the `account` parameter in the other APIs :)

**Comment by ralbertazzi** [comment]
Regarding the issue with the state, I imported a Connect webhook that is however recognized in the state as a non-webhook endpoint. Therefore if I don't want to have diffs (which is my end goal) I need to set (or use the default) `connect = false`. However if I change it to `connect = true` - which I'm doing just to reflect the actual real state of the webhook on Stripe - Terraform wants to destroy and recreate the webhook. Instead what I would expect is:
- Setting `connect = true` should produce no changes, since the webhook is indeed a Connect webhook
- Setting `connect = false` (or keeping the default) should ask to destroy and re-create my existing Connect webhook

**Comment by lukasaron** [comment]
Hi @ralbertazzi ,

Thank You for the confirmation regarding the `application` field. I would consider this one as understood and ready for implementation.

The second part is a bit confusing for me. Please bare with me, as my intentions are clear and I would like to implement this right. Your last message is pointing to `account` field which I don't have in the Stripe response. My assumption is that you meant `application` field. When my assumption is correct I should set the `connect` field to `true` when the `application` field is populated. In other words:

```
d.Set("connect", webhookEndpoint.Application != "")
```

Could you please confirm that my assumption is correct? 

Thanks for your help @ralbertazzi!
Lukas

**Comment by lukasaron** [comment]
Hi @ralbertazzi,

Please try the latest version of the Terraform Stripe provider [3.2.2].

Cheers,
Lukas

**Comment by ralbertazzi** [comment]
@lukasaron it's fixed 🚀 

After upgrading the provider and running `terraform apply`, I was prompted that my Connect webhook - that I was tracking on Terraform with `connect = false` because of the bug - was going to be deleted and recreated. After changing `connect = true` and re-running `terraform apply` I was finally welcomed with the desired `No changes` from terraform 💪 

I also tried creating a _new_ Connect account and refreshing its state and things work as expected. I will consider this issue closed, thanks a lot for your support!!

**Comment by lukasaron** [comment]
Thanks, @ralbertazzi  for helping me achieve this fix!
