### ISSUE TITLE
support for billing meters

### ISSUE THREAD

**Issue by dbarrosop** [lukasaron/terraform-provider-stripe#82]
Hello,
would it be possible to add support for meters?

https://docs.stripe.com/billing/subscriptions/usage-based/recording-usage#configuring-meter

API:

https://docs.stripe.com/api/billing/meter/create
https://docs.stripe.com/api/prices/create (needs the recurring.meter option to attach a meter)

Thanks!

**Comment by lukasaron** [comment]
Hi @dbarrosop ,

Thank you for proposing this.

**Comment by dbarrosop** [comment]
Hi @lukasaron,
do you know when you may be releasing a new version with this functionality? No rush, we just want to know as currently we are having to deal with a development override adding a bit of complexity to our CI.

Thanks!
